/////////////////////////////////////////////////////////////////////////////////////////
// This script works solely for characters made by                                     //
// http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator/#?sex=female //
// with an xml generated by http://sourceforge.net/projects/spritedecompose/.         //
/////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Usages: node xmlToPlist -u FILE_NAME -s DIRECTORY                                                                      //
// FILE_NAME is the name of the xml file without the extension, it assumes that the matching png file is of FILE_NAME.png //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

var fs = require('fs');
var minimist = require('minimist')(process.argv.slice(2));
var xml = fs.readFileSync(minimist.s + minimist.n + '.xml', 'utf8');
var _ = require('lodash');
var lines = xml.split('\n');
lines = lines.slice(3, lines.length - 3);

/**
 * Parses a single line in a xml, to extrac the width, height and coords in the sheet.
 * @param  {String} line A line in the xml.
 * @return {Object}      An object with all the information extracted.
 */
var parse = function(line) {
    var pattern = /\<cut w=\"(.*)\" x=\"(.*)\" y=\"(.*)\" h=\"(.*)\" row=\"(.*)\" col=\"(.*)\"\/\>/;
    var query = pattern.exec(line);
    return {
        width: parseInt(query[1]),
        height: parseInt(query[4]),
        x: parseInt(query[2]),
        y: parseInt(query[3])
    };
};

var data = lines.map(parse);

/**
 * Gives a name to each animation in the spritesheet.
 * @type {Array}
 */
var metaData = [{
    count: 7,
    type: 'spell-front'
}, {
    count: 7,
    type: 'spell-left'
}, {
    count: 7,
    type: 'spell-front'
}, {
    count: 7,
    type: 'spell-right'
}, {
    count: 8,
    type: 'stab-front'
}, {
    count: 8,
    type: 'stab-left'
}, {
    count: 8,
    type: 'stab-front'
}, {
    count: 8,
    type: 'stab-right'
}, {
    count: 9,
    type: 'walk-front'
}, {
    count: 9,
    type: 'walk-left'
}, {
    count: 9,
    type: 'walk-front'
}, {
    count: 9,
    type: 'walk-right'
}, {
    count: 6,
    type: 'swing-front'
}, {
    count: 6,
    type: 'swing-left'
}, {
    count: 6,
    type: 'swing-front'
}, {
    count: 6,
    type: 'swing-right'
}, {
    count: 13,
    type: 'arrow-front'
}, {
    count: 13,
    type: 'arrow-left'
}, {
    count: 13,
    type: 'arrow-front'
}, {
    count: 13,
    type: 'arrow-right'
}, {
    count: 6,
    type: 'die'
}];

/**
 * Adds a name to a single animation.
 * @param  {String} type  The type of animation.
 * @param  {Number} index Within the type the unique index.
 * @return {String}       An unique name.
 */
var makeName = function(type, index) {
    return minimist.n + '-' + type + '/' + index + '.png';
};

/**
 * Adds to which type a single animation belongs.
 * @param {Array} entries Array as parsed by 'parse'.
 */
var addType = function(entries) {
    var entryIndex = 0;
    metaData.forEach(function(meta) {
        for (var index = 0; index < meta.count; index++) {
            entries[entryIndex].type = meta.type;
            entryIndex++;
        }
    });
};

/**
 * Adds a name to each animation
 * @param {Array} entries Array as parsed by 'parse' and then by 'addType'.
 */
var addName = function(entries){
    var index = 0;
    var current = entries[0].type;
    entries.forEach(function(entry){
        if(entry.type !== current) {
            current = entry.type;
            index = 0;
        }
        entry.name = makeName(entry.type, index);
        index++;
    });
}

// Add the types
addType(data);

// Sorty in each type of animation by the x coord
data = _.sortByAll(data, ['type', 'x']);

// Add an unique name to each animation
addName(data);


//////////////////////////////////////////////////////////////////////
// Below converts the array to plist which can be used by cocos2d-x //
//////////////////////////////////////////////////////////////////////

var header = '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n\t<dict>\n\t\t<key>frames</key>\n\t\t<dict>';
var footer = '\n\t</dict>\n</plist>';

/**
 * Makes a xml tag with a given tabsize infront of it.
 * @param  {Number} tabSize Number of tabs to lead.
 * @param  {String} prop    The property of the xml tag.
 * @param  {String} value   The value of the xml tag.
 * @return {String}         Xml tag as: <prop>value</prop>
 */
var makeTag = function(tabSize, prop, value) {
    var tabs = '';
    for (var i = 0; i < tabSize; i++) tabs += '\t';
    return tabs + '<' + prop + '>' + value + '</' + prop + '>';
}

/**
 * Makes a key string xml tag
 * @param  {Number} tabSize Number of tabs to lead.
 * @param  {String} keyValue     The key value
 * @param  {String} stringValue  The string value
 * @return {String}         Xml tag: <key>keyValue</key><string>stringValue</string>
 */
var makeKeyString = function(tabSize, keyValue, stringValue) {
    return [makeTag(tabSize, 'key', keyValue), makeTag(tabSize, 'string', stringValue)].join('\n');
}

/**
 * Makes a dict entry for the plist
 * @param  {Object} row The data for the dict.
 * @return {String}     An xml dict element.
 */
var makeEntry = function(row) {
    return [makeTag(3, 'key', row.name),
        '\t\t\t<dict>',
        makeKeyString(4, 'frame', '{{' + row.x + ',' + row.y + '},{' + row.width + ',' + row.height + '}}'),
        makeKeyString(4, 'offset', '{0,0}'),
        makeTag(4, 'key', 'rotated'),
        '\t\t\t\t<false/>',
        makeKeyString(4, 'sourceColorRect', '{{0,0},{' + row.width + ',' + row.height + '}}'),
        makeKeyString(4, 'sourceSize', '{' + row.width + ',' + row.height + '}'),
        '\t\t\t</dict>'
    ].join('\n');
};

/**
 * The metadata for cocos2d-x to be parsed.
 * @param  {String} png   The png file name.
 * @param  {Number} sizeX The x size of the png.
 * @param  {Number} sizeY The y size of the png.
 * @return {String}       Xml metadata.
 */
var makeMetaData = function(png, sizeX, sizeY) {
    return [makeTag(2, 'key', 'metadata'),
        '\t\t<dict>',
        makeKeyString(3, 'format', 2),
        makeKeyString(3, 'realTextureFileName', png),
        makeKeyString(3, 'size', '{' + sizeX + ',' + sizeY + '}'),
        makeKeyString(3, 'textureFileName', png),
        '\t\t</dict>'
    ].join('\n');
};

var xml = header + '\n' +data.map(makeEntry).join('\n') + '\t\t</dict>\n' + makeMetaData(minimist.n + '.png', 832, 1344) + '\n' +footer;
fs.writeFileSync(minimist.s + minimist.n + '.plist', xml, 'utf8');
